weights: ./yolov5/weights/yolov5s.pt
cfg: ''
data: detection_names_and_prices/data/settings.yaml
hyp: ./yolov5/data/hyp.scratch.yaml
epochs: 200
batch_size: 32
img_size:
- 320
- 320
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
logdir: detection_names_and_prices/runs/train
name: basic_320
log_imgs: 10
workers: 8
total_batch_size: 32
world_size: 1
global_rank: -1
